apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ij3bm9qbx-dotnet-basic
  janus-idp.io/tekton: ij3bm9qbx-dotnet-basic
  backstage.io/kubernetes-id: ij3bm9qbx-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ij3bm9qbx-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
